version: '3'
services:
  slimevr_database:
    container_name: slimevr_database
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: slimevr
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: slimevr
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - database_volume:/var/lib/postgresql/data
    networks:
      - slimevr_network
  slimevr_api:
    build:
      context: .
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    expose:
       - 3000:3000
    depends_on:
      - slimevr_database
      - slimevr-api-s3
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    networks:
      - slimevr_network
      - caddy_network
    environment:
      APP_ENV: ${APP_ENV}
      LISTEN_HOST: ${LISTEN_HOST}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_BUILDS_BUCKET: ${S3_BUILDS_BUCKET}
  slimevr-api-s3:
    image: minio/minio:latest
    expose:
      - "9000:9000"
      - "9099:9099"
    environment:
      MINIO_ACCESS_KEY_FILE: access_key
      MINIO_SECRET_KEY_FILE: secret_key
    volumes:
      - storage-minio:/data
    secrets:
     - access_key
     - secret_key
    command: server --address ":9099" --console-address ":9000" /data/disk{1...4}
    restart: always
    networks:
      - slimevr_network
      - caddy_network
  slimevr_api_s3_init:
    image: minio/mc
    depends_on:
      - slimevr-api-s3
    networks:
      - slimevr_network
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add slimevr http://slimevr-api-s3:9099 SLIMEVRACCESS SLIMEVRSECRET;
      /usr/bin/mc mb slimevr/slimevr-firmware-builds;
      /usr/bin/mc policy set public slimevr/slimevr-firmware-builds;
      exit 0;
      "

volumes:
  database_volume:
  storage-minio:
    external: false

secrets:
  access_key:
    file: ./docker/minio/access_key.txt
  secret_key:
    file: ./docker/minio/secret_key.txt

networks:
  slimevr_network:
  caddy_network:
    external: true